name: lincs 
channels:
  - conda-forge
  - defaults
dependencies:
  - attrs=19.1.0
  - backcall=0.1.0
  - blas=1.0
  - bleach=3.1.0
  - bokeh=1.2.0
  - ca-certificates=2019.3.9
  - certifi=2019.3.9
  - click=7.0
  - cloudpickle=1.1.1
  - cycler=0.10.0
  - cytoolz=0.9.0.1
  - dask=1.2.2
  - dask-core=1.2.2
  - dbus=1.13.6
  - decorator=4.4.0
  - defusedxml=0.6.0
  - distributed=1.28.1
  - entrypoints=0.3
  - expat=2.2.6
  - fontconfig=2.13.0
  - freetype=2.9.1
  - glib=2.56.2
  - gmp=6.1.2
  - gst-plugins-base=1.14.0
  - gstreamer=1.14.0
  - h5py=2.9.0
  - hdf5=1.10.4
  - heapdict=1.0.0
  - icu=58.2
  - intel-openmp=2019.4
  - ipykernel=5.1.1
  - ipython=7.5.0
  - ipython_genutils=0.2.0
  - jedi=0.13.3
  - jinja2=2.10.1
  - joblib=0.13.2
  - jpeg=9b
  - jsonschema=3.0.1
  - jupyter_client=5.2.4
  - jupyter_core=4.4.0
  - jupyterlab=0.35.5
  - jupyterlab_server=0.2.0
  - kiwisolver=1.1.0
  - libedit=3.1.20181209
  - libffi=3.2.1
  - libgcc-ng=8.2.0
  - libgfortran-ng=7.3.0
  - libpng=1.6.37
  - libsodium=1.0.16
  - libstdcxx-ng=8.2.0
  - libtiff=4.0.10
  - libuuid=1.0.3
  - libxcb=1.13
  - libxml2=2.9.9
  - llvmlite=0.28.0
  - locket=0.2.0
  - markupsafe=1.1.1
  - matplotlib=3.1.0
  - mistune=0.8.4
  - mkl=2019.4
  - mkl-service=2.0.2
  - mkl_fft=1.0.12
  - mkl_random=1.0.2
  - msgpack-python=0.6.1
  - nbconvert=5.5.0
  - nbformat=4.4.0
  - ncurses=6.1
  - notebook=5.7.8
  - numba=0.43.1
  - numpy=1.16.4
  - numpy-base=1.16.4
  - olefile=0.46
  - openssl=1.1.1b
  - packaging=19.0
  - pandas=0.24.2
  - pandoc=2.2.3.2
  - pandocfilters=1.4.2
  - parso=0.4.0
  - partd=0.3.10
  - pcre=8.43
  - pexpect=4.7.0
  - pickleshare=0.7.5
  - pillow=6.0.0
  - pip=19.1.1
  - prometheus_client=0.6.0
  - prompt_toolkit=2.0.9
  - psutil=5.6.2
  - ptyprocess=0.6.0
  - pygments=2.4.2
  - pyparsing=2.4.0
  - pyqt=5.9.2
  - pyrsistent=0.14.11
  - python=3.6.8
  - python-dateutil=2.8.0
  - pytz=2019.1
  - pyyaml=5.1
  - pyzmq=18.0.0
  - qt=5.9.7
  - readline=7.0
  - scikit-learn=0.21.2
  - scipy=1.2.1
  - send2trash=1.5.0
  - setuptools=41.0.1
  - sip=4.19.8
  - six=1.12.0
  - sortedcontainers=2.1.0
  - sqlite=3.28.0
  - tblib=1.4.0
  - terminado=0.8.2
  - testpath=0.4.2
  - tk=8.6.8
  - toolz=0.9.0
  - tornado=6.0.2
  - traitlets=4.3.2
  - umap-learn=0.3.9
  - wcwidth=0.1.7
  - webencodings=0.5.1
  - wheel=0.33.4
  - xz=5.2.4
  - yaml=0.1.7
  - zeromq=4.3.1
  - zict=0.1.4
  - zlib=1.2.11
  - zstd=1.3.7
  - pip:
    - absl-py==0.7.1
    - astor==0.8.0
    - gast==0.2.2
    - google-pasta==0.1.7
    - grpcio==1.21.1
    - keras-applications==1.0.8
    - keras-preprocessing==1.1.0
    - markdown==3.1.1
    - protobuf==3.8.0
    - tb-nightly==1.14.0a20190301
    - tensorflow-gpu==2.0.0a0
    - termcolor==1.1.0
    - tf-estimator-nightly==1.14.0.dev2019030115
    - werkzeug==0.15.4

