data_dir: ../data/GSE92742_Broad_LINCS/

data:
    file: Level3_INF_mlr12k_n1319138x12328.gctx
    sample_index_name: inst_id
    gene_index_name: gene_id

sample_metadata:
    main:
        name: inst_info
        file: inst_info.txt
        index_col: inst_id
        usecols:
            - inst_id
            - cell_id
            - pert_id
            - pert_iname
            - pert_type 
#             - pert_dose
#             - pert_dose_unit 
#             - pert_time
#             - pert_time_unit 
#             - rna_plate
#             - rna_well
        na_values: "-666"
        sep: "\t"
    lookup:
        - name: cell_info
          file: cell_info.txt
          lookup_key: cell_id
          usecols: 
              - cell_id 
              - cell_type 
              - precursor_cell_id
              - modification 
              - sample_type 
              - primary_site 
              - subtype
              - original_growth_pattern 
              - original_source_vendor
              - donor_age 
              - donor_sex
              - donor_ethnicity 
#               - provider_catalog_id
#               - base_cell_id 
          na_values: "-666"
          sep: "\t"
        - name: pert_info
          file: pert_info.txt
          lookup_key: pert_id
          usecols:
              - pert_id
              - inchi_key_prefix 
              - inchi_key
              - canonical_smiles
#               - pubchem_cid
#               - pert_iname 
#               - pert_type
#               - is_touchstone
          na_values: "-666"
          sep: "\t"

gene_metadata:
    main:
        name: gene_info
        file: gene_info.txt
        index_col: gene_id
        usecols:
            - gene_id 
            - gene_symbol 
            - gene_title 
#             - is_lm
#             - is_bing
        na_values: "-666"
        sep: "\t"